[profile.default]
solc_version = '0.8.15'
auto_detect_solc = false
optimizer = true
optimizer_runs = 1_000
fuzz_runs = 1_000
remappings = [
  "forge-std=lib/forge-std/src/",
  "solmate=lib/solmate/src/",
  "vrgdas=lib/VRGDAs/src/",
]

[profile.ci]
fuzz_runs = 100_000